#!/bin/zsh

#TODO: Уборка

## --------------------------------
## Алиасы для разворачивания dotfiles:
alias dotfiles='/usr/bin/git --git-dir=/home/trefmanic/.dotfiles/ --work-tree=/home/trefmanic'
## --------------------------------

## Алиасы пользователя
## --------------------------------

## Улучшаем поведение ls
alias ls='ls -BhFC --group-directories-first --color'
alias lh='ls -ldh .?*'

## Уведомление для долго выполняющихся комманд
## Использовать так:
## sleep 10; alert
## TODO: Перенести в функции
alias "alert"='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal \
|| echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

## Python REPL
alias 'pyrepl'="echo '' | fzf --print-query --preview 'python3 -c {q}'"

# Зачем nano, если есть emacs?
alias "nano"='emacs'

# Погода в терминале
CITY='Губкинский'
alias wth='curl -s "wttr.in/$CITY?Q2n&lang=ru" | grep -v "@"'
alias wthn='curl -s "wttr.in/$CITY?Q0n&lang=ru" | grep -v "@"'

# Правка конфигов zsh
alias "edzsh"='emacs ~/.zshrc'

alias activate='source .venv/bin/activate'

# Алиасы для расширений

alias -s txt=st

# Алиас для mpv

alias "mplayer"='mpv --hwdec'

# Алиас для ncmpcpp
alias music='ncmpcpp'
# Алиасы для sudo
alias su='sudo -E -s'
alias please='sudo -E'

# Локальный шрифт для figlet
alias figlet='figlet -d ~/.local/share/figlet/fonts'

# Часы
alias clock="tty-clock -s -c -C 4 -b"
# Секундомер/таймер
alias termdown="termdown -a -f clb8x10"
# gotop
alias gotop="gotop -c zenburn"
# Сортировать по IP-адресам
alias ipsort="sort -n -t . -k 1,1 -k 2,2 -k 3,3 -k 4,4"
# Алиас для синтеза речи (echo "Тест" | say)
alias say="RHVoice-client -s Elena+CLB | aplay -q"
# Замена youtube-dl на yt-dlp для совместимости
alias "youtube-dl"="yt-dlp"
alias "xshare"="xclip -o | qrencode -t utf8"
# Алиасы для wireguard
alias "wgup"="wg-quick up wg0"
alias "wgdown"="wg-quick down wg0"
alias "uphugo"="hugo && rsync --progress -rltuzv -e 'ssh -p 38283' ./public/* trefmanic@trefmanic.me:/home/trefmanic/trefmanic.me/"
alias now='echo "$(date +%d-%m-%Y-%H%M%S)"'
# Последний коммит
alias -g "lastlog"="log --name-status HEAD^..HEAD"
