#!/bin/zsh
## Пользовательские настройки -----
export LANG=ru_RU.UTF-8
export TERM=xterm-256color
## Флаги компиляции
export ARCHFLAGS="-arch x86_64"
## Настройки клиента SSH
export SSH_KEY_PATH="~/.ssh/rsa_id"
## Настройки GPG
export GPG_TTY=$(tty)
## Добавление ~/.local/bin в PATH
export PATH="$PATH:$HOME/.local/bin"
## Настройки RVM
export PATH="$PATH:$HOME/.rvm/bin"
export PYTHONWARNINGS=ignore:DEPRECATION
## ---------------------------------

## Настройки zsh -------------------
## Дополнение с учётом регистра
CASE_SENSITIVE="true"
DISABLE_AUTO_UPDATE="false"
## Исправление неверно введённых команд
ENABLE_CORRECTION="false"
## Настройка дополнения по Tab
zstyle ':completion:*' menu select
zstyle ':completion:*' list-colors ''
# Command not found hook
if [[ -s '/etc/zsh_command_not_found' ]]; then
    source '/etc/zsh_command_not_found'
fi
## ---------------------------------

## Персональные настройки ----------
export DEBEMAIL=trefmanic@gmail.com
export MANPAGER="sh -c 'col -b | bat -l man -p'"
## Центрирование вывода на полном экране
# export LESSOPEN="|- lesspage %s"
## Должно соответствовать параметру WIDTH
## заданному в .local/bin/lesspage
export MANWIDTH="100"

# Редакторы для локальных и удалённых сеансов
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='nano'
else
  export EDITOR='emacs'
fi
export HASTE_URL="haste.trefmanic.me"
## ---------------------------------

## Опции FZF
export FZF_DEFAULT_COMMAND="find -L * -path '*/\.*' -prune -o -type f -print -o -type l -print 2> /dev/null"
export BINARY_FILE='\033[01;32m'$(figlet binary)'\033[00m'
FZF_PREVIEW_OPTIONS='--border --ansi --height=60 --preview="[[ $(file --mime {}) =~ binary ]] && echo $BINARY_FILE || bat --style=numbers --color=always {}" --preview-window=right:50%:wrap'
export FZF_CTRL_T_OPTS=$FZF_PREVIEW_OPTIONS
export FZF_CTRL_R_OPTS='--border --ansi --height=60%'
export FZF_COMPLETION_OPTS=$FZF_CTRL_R_OPTS

## Поддержка редактирования длинных команд
## и последовательностей комманд
autoload -U edit-command-line
zle -N edit-command-line
bindkey '^Ex' edit-command-line
bindkey '^E^X' edit-command-line

## Устанавливаем заголовок окна Terminator
title $USER@$HOST
