#!/bin/zsh
# Пользовательские настройки

# Дополнение с учётом регистра
CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="false"

# Исправление неверно введённых команд
ENABLE_CORRECTION="false"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

export DEBEMAIL=trefmanic@gmail.com
export TERM=xterm-256color
export MANPAGER="sh -c 'col -b | bat -l man -p'"

# Локаль
export LANG=ru_RU.UTF-8

# Редакторы для локальных и удалённых сеансов
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='nano'
else
  export EDITOR='emacs'
fi

# Command not found hook
if [[ -s '/etc/zsh_command_not_found' ]]; then
    source '/etc/zsh_command_not_found'
fi

# Compilation flags
export ARCHFLAGS="-arch x86_64"

# ssh
export SSH_KEY_PATH="~/.ssh/rsa_id"

# Опции для Python
export PYTHONWARNINGS=ignore:DEPRECATION
export GPG_TTY=$(tty)

# Опции FZF
export FZF_DEFAULT_COMMAND="find -L * -path '*/\.*' -prune -o -type f -print -o -type l -print 2> /dev/null"
export BINARY_FILE='\033[01;32m'$(figlet binary)'\033[00m'

# Опции для предпросмотра
FZF_PREVIEW_OPTIONS='--border --ansi --height=60 --preview="[[ $(file --mime {}) =~ binary ]] && echo $BINARY_FILE || bat --style=numbers --color=always {}" --preview-window=right:50%:wrap'

export FZF_CTRL_T_OPTS=$FZF_PREVIEW_OPTIONS

export FZF_CTRL_R_OPTS='--border --ansi --height=60%'

export FZF_COMPLETION_OPTS=$FZF_CTRL_R_OPTS

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

## Устанавливаем заголовок окна Terminator
title $USER@$HOST
