#!/bin/zsh
## Вспомогательные функции

## Окрашивание для префиксов
function zclr(){
    message=$1
    color=$2
    print -P "%F{$color}$message%f"
}

SPACESHIP_PROMPT_ORDER=(
    host
    user
    exec_time
    venv
    git
    pyenv
    dir
    line_sep
    jobs
    exit_code
    time
    char
)
## Общие настройки
SPACESHIP_CHAR_SYMBOL=$(zclr '» ' cyan)

## Настройки модулей
## SPACESHIP_TIME
SPACESHIP_TIME_SHOW='true'
SPACESHIP_TIME_COLOR='green'
SPACESHIP_TIME_PREFIX=''
## SPACESHIP_HOST
SPACESHIP_HOST_SHOW='always'
SPACESHIP_HOST_PREFIX=''
SPACESHIP_HOST_COLOR='white' # Хаки (цвет)
SPACESHIP_HOST_COLOR_SSH='red'
## SPACESHIP_DIR
SPACESHIP_DIR_PREFIX=$(zclr '> ' yellow)
SPACESHIP_DIR_COLOR='yellow'
## SPACESHIP_VENV
SPACESHIP_VENV_GENERIC_NAMES='( .venv )'
SPACESHIP_VENV_PREFIX=$(zclr 'ω ' cyan)
SPACESHIP_VENV_COLOR='cyan'
## SPACESHIP_EXEC_TIME
SPACESHIP_EXEC_TIME_PREFIX=$(zclr 'Δt ' magenta)
SPACESHIP_EXEC_TIME_COLOR='magenta'
## SPACESHIP_GIT
SPACESHIP_GIT_PREFIX=''
