#!/bin/zsh

# Конфигурация PowerLevel9k
###########################

# Перенос приглашения на новую строку
POWERLEVEL9K_PROMPT_ON_NEWLINE=true

# Символ приглашения пользователя
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="╰» "

# Добавление новой строки после команды
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

# # Модуль отображения текущего трека
# #----------------------------------
# if (( $UID !=0 )) then
# 	POWERLEVEL9K_CUSTOM_CURRENT_TRACK="zsh_current_track"
# else
# 	POWERLEVEL9K_CUSTOM_CURRENT_TRACK=""
# fi
# #----------------------------------

#POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context history time custom_current_track dir )

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context time dir)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(vcs virtualenv)

# Сокращение имени каталога
POWERLEVEL9K_SHORTEN_DIR_LENGTH=5
POWERLEVEL9K_SHORTEN_STRATEGY=truncate_from_right

POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND="red"
POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND="black"

POWERLEVEL9K_TIME_BACKGROUND="green"

POWERLEVEL9K_VIRTUALENV_BACKGROUND="green"

#POWERLEVEL9K_PYTHON_ICON=$'\uF058 '
#POWERLEVEL9K_VCS_GIT_ICON=$'\uF1D2'

POWERLEVEL9K_PYTHON_ICON='🐍'
POWERLEVEL9K_VCS_GIT_ICON=$'\u276E\u276E'

#POWERLEVEL9K_CUSTOM_CURRENT_TRACK_BACKGROUND="green"
